steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/flask-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/flask-app"]
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "deployment.yaml"]
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "service.yaml"]
images:
  - "gcr.io/$PROJECT_ID/flask-app"
options:
    logging: NONE
